### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Roddyville** [ArunyaGoojar/RunAsDate-for-MacOS#1]
Howzit bro pls can you assist me with RunAsDate pls

**Comment by arunyagoojar** [comment]
Did you follow the steps , its pretty straightforward . I have written detailed instructions.

**Comment by Roddyville** [comment]
Yes but I have the old school mac pro that doesn't take shortcuts 



Get BlueMail for Android

**Comment by arunyagoojar** [comment]
you can try and make a shell script and run it using terminal .
Refer to this : https://blog.kandji.io/guide-for-apple-it-introduction-to-mac-scripting

**Comment by Roddyville** [comment]
Thanks bruv
